In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.ones((6,6),dtype = np.int32)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [4]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [5]:
x = np.ones((2,4,5))
x

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [6]:
y = np.zeros_like(x)

In [7]:
np.concatenate((x,y))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [8]:
a = np.linspace(1,55,4)
a

array([ 1., 19., 37., 55.])

In [9]:
b = np.linspace(1,10,4,endpoint = False)
b

array([1.  , 3.25, 5.5 , 7.75])

In [10]:
c = np.concatenate((a,b))
c

array([ 1.  , 19.  , 37.  , 55.  ,  1.  ,  3.25,  5.5 ,  7.75])

In [11]:
a = np.ones((2,3,4),dtype = np.int32)
a.reshape((3,8))

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [12]:
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [13]:
a.resize((3,8))
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [14]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [15]:
a = np.ones((2,3,4),dtype = np.int32)
a.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [16]:
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [17]:
a = np.ones((2,4,4),dtype = np.int)

b = a.astype(np.float)#can used as copy
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [18]:
a = np.full((2,3,4),25,dtype = int)
a

array([[[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]],

       [[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]]])

In [19]:
a.tolist()

[[[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]],
 [[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]]]

In [20]:
#索引，切片
a = np.array([9,8,7,6,5])
a[2]

7

In [21]:
a[1:5:3]

array([8, 5])

In [22]:
a = np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [23]:
a[1,2,3]#每个维度的序号

23

In [24]:
a[0,1,2]

6

In [25]:
a[-1,-2,-3]

17

In [26]:
a[:,1,-3]#:切片

array([ 5, 17])

In [27]:
a[:,1:3,:]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
a[:,:,::2]#步长

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])

In [29]:
a.mean()

11.5

In [30]:
a = a/a.mean()
a

array([[[0.        , 0.08695652, 0.17391304, 0.26086957],
        [0.34782609, 0.43478261, 0.52173913, 0.60869565],
        [0.69565217, 0.7826087 , 0.86956522, 0.95652174]],

       [[1.04347826, 1.13043478, 1.2173913 , 1.30434783],
        [1.39130435, 1.47826087, 1.56521739, 1.65217391],
        [1.73913043, 1.82608696, 1.91304348, 2.        ]]])

In [31]:
a = np.arange(24).reshape((2,3,4))

np.square(a)

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]], dtype=int32)

In [32]:
a = np.sqrt(a)
a

array([[[0.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131],
        [2.82842712, 3.        , 3.16227766, 3.31662479]],

       [[3.46410162, 3.60555128, 3.74165739, 3.87298335],
        [4.        , 4.12310563, 4.24264069, 4.35889894],
        [4.47213595, 4.58257569, 4.69041576, 4.79583152]]])

In [33]:
np.modf(a)

(array([[[0.        , 0.        , 0.41421356, 0.73205081],
         [0.        , 0.23606798, 0.44948974, 0.64575131],
         [0.82842712, 0.        , 0.16227766, 0.31662479]],
 
        [[0.46410162, 0.60555128, 0.74165739, 0.87298335],
         [0.        , 0.12310563, 0.24264069, 0.35889894],
         [0.47213595, 0.58257569, 0.69041576, 0.79583152]]]),
 array([[[0., 1., 1., 1.],
         [2., 2., 2., 2.],
         [2., 3., 3., 3.]],
 
        [[3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]]]))

In [34]:
a = np.arange(24).reshape((2,3,4))
b = np.sqrt(a)

In [35]:
np.maximum(a,b)

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [36]:
a > b

array([[[False, False,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [37]:
 np.random.randn(3,6,5)

array([[[-0.80327625, -2.51824858,  0.42897815,  1.86488048,
          0.04922043],
        [ 1.97218185,  0.25398605, -1.14305433,  2.35091144,
          1.12861227],
        [ 0.91325595, -0.80237051, -1.07844125, -0.88496146,
          2.02820741],
        [ 0.06610789,  0.02672855,  0.95264   , -0.38880278,
         -1.3816674 ],
        [-1.22354664, -0.25967283, -1.14184876,  0.35338392,
         -0.46205017],
        [-0.21639873, -0.40598024,  0.33102753, -0.26656391,
          0.2549158 ]],

       [[-0.03757857, -0.92260603, -1.36638245,  0.30725916,
          0.59157288],
        [-0.96093189,  0.74974282, -0.6168852 , -0.15927108,
         -0.40870008],
        [ 0.4977653 , -1.58174666, -0.68486327,  0.129812  ,
         -0.17017533],
        [-0.99896623, -1.99764638,  0.16216841, -0.38225245,
          0.81868033],
        [-0.20441637,  2.22686752, -0.32402339,  0.35092945,
         -0.32596399],
        [-1.86239141, -0.08549098, -0.6687764 , -0.90012685,
          0.3

In [38]:
np.random.randint(100,200,(3,4))

array([[166, 151, 135, 129],
       [151, 143, 111, 108],
       [185, 184, 120, 121]])

In [39]:
np.random.seed(10)
np.random.randint(100,200,(3,4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [40]:
a = np.random.randint(100,200,(3,4))
a

array([[116, 111, 154, 188],
       [162, 133, 172, 178],
       [149, 151, 154, 177]])

In [41]:
np.random.shuffle(a)
a

array([[116, 111, 154, 188],
       [149, 151, 154, 177],
       [162, 133, 172, 178]])

In [42]:
np.random.shuffle(a)
a

array([[162, 133, 172, 178],
       [116, 111, 154, 188],
       [149, 151, 154, 177]])

In [43]:
np.random.permutation(a)

array([[149, 151, 154, 177],
       [162, 133, 172, 178],
       [116, 111, 154, 188]])

In [44]:
a

array([[162, 133, 172, 178],
       [116, 111, 154, 188],
       [149, 151, 154, 177]])

In [49]:
b = np.random.randint(100,200,(8,))
b

array([118, 180, 171, 188, 111, 117, 146, 107])

In [46]:
np.random.choice(b,(3,2))

array([[112, 189],
       [130, 165],
       [165, 131]])

In [51]:
np.random.choice(b,(3,2),replace = False)

array([[117, 107],
       [118, 171],
       [146, 180]])

In [53]:
np.random.choice(b,(3,2),p = b/np.sum(b))

array([[117, 146],
       [171, 111],
       [146, 107]])

In [55]:
u = np.random.uniform(0,10,(3,4)) #均匀分布，0-10
u

array([[3.97164523, 6.37951564, 3.72519952, 0.02406761],
       [5.48816356, 1.26971841, 0.79792681, 2.35038596],
       [6.59964947, 2.14953192, 2.03046616, 3.82865111]])

In [57]:
n = np.random.normal(10,5,(3,4))#正态分布，均值，标准差，形状
n

array([[ 7.17283661, 10.03925114,  4.36604546, 17.56907998],
       [ 6.96352757, 12.09161148, 14.93278376,  8.49320482],
       [ 9.91183261, 12.99558049,  8.48697357,  6.27267071]])

In [64]:
p = np.random.poisson(50,(3,4))#泊松分布，随机事件发生率，形状
p

array([[44, 53, 48, 60],
       [59, 56, 44, 48],
       [57, 58, 46, 46]])

In [66]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
np.sum(a)

105

In [68]:
np.mean(a)

7.0

In [69]:
np.mean(a,axis=1)

array([ 2.,  7., 12.])

In [70]:
np.average(a,axis=0,weights =[10,5,1] )

array([2.1875, 3.1875, 4.1875, 5.1875, 6.1875])

In [72]:
b = np.arange(15,0,-1).reshape(3,5)
b

array([[15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [73]:
np.max(b)

15

In [74]:
np.argmax(b)

0

In [75]:
np.argmin(b)

14

In [77]:
np.unravel_index(np.argmax(b),b.shape)#根据shape将一维下标转化成多维下标

(0, 0)

In [80]:
a = np.random.randint(0,20,(5))
a

array([18,  2, 11, 14, 10])

In [81]:
np.gradient(a)#梯度，[a,b,c],gradient = (a + c)/2 

array([-16. ,  -3.5,   6. ,  -0.5,  -4. ])

In [83]:
c = np.random.randint(0,50,(3,5))
c

array([[36,  6,  3, 34, 21],
       [16, 39, 18, 21, 23],
       [19,  7, 16,  3, 38]])

In [84]:
np.gradient(c)

[array([[-20. ,  33. ,  15. , -13. ,   2. ],
        [ -8.5,   0.5,   6.5, -15.5,   8.5],
        [  3. , -32. ,  -2. , -18. ,  15. ]]),
 array([[-30. , -16.5,  14. ,   9. , -13. ],
        [ 23. ,   1. ,  -9. ,   2.5,   2. ],
        [-12. ,  -1.5,  -2. ,  11. ,  35. ]])]